#!/usr/bin/env bash

# Variables
config=$HOME/.config/hypr
scripts=$config/scripts

# Waybar
pkill waybar
$scripts/launch_waybar &
$scripts/tools/dynamic &

# Wallpaper
setsid swww-daemon
swww kill
swww init
swww img ~/Downloads/bg.jpg

# Dunst (Notifications)
dunst &

setsid fcitx5

# Cursor
hyprctl setcursor Bibata-Modern-Ice 24

# Others
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
